version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data_interests:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8080
      POSTGRES_DB: polling
      POSTGRES_HOST: localhost

  back:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data_interests: