# Generated by Django 2.2.10 on 2021-03-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_question_question_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('poll', 'question_number')},
        ),
    ]
