# Generated by Django 2.2.10 on 2021-03-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20210309_2344'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userquestion',
            unique_together=set(),
        ),
    ]
