# Generated by Django 2.2.10 on 2021-03-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20210310_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_number',
        ),
    ]
