# Generated by Django 2.2.10 on 2021-03-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_remove_question_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(related_name='polls', to='polls.Question'),
        ),
    ]
