# Generated by Django 2.2.10 on 2021-03-09 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20210310_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='users',
            field=models.ManyToManyField(related_name='polls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='questions', to='polls.Answer'),
        ),
    ]
