# Generated by Django 2.2.10 on 2021-03-10 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0019_auto_20210310_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='users'
        ),
        migrations.AddField(
            model_name='poll',
            name='users',
            field=models.ManyToManyField(related_name='polls', through='polls.UserPoll', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.UserPoll'),
            preserve_default=False,
        ),
    ]
